title: Angelica Chen
description: angelica[dot]chen[at]nyu.edu<br><a href="https://www.semanticscholar.org/author/Angelica-Chen/13336152">Semantic Scholar profile</a>
logo: /headshot1.jpg
remote_theme: pages-themes/minimal@v0.2.0
google_analytics: G-670B6DTP1R
plugins:
- jekyll-remote-theme
